In [18]:
import numpy as np
from numpy.random import randint


In [3]:
data=[10,15,30,45,60]
np.array(data)

array([10, 15, 30, 45, 60])

In [4]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(50,100,5)

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [40]:
np.random.randint(10,30,5)

array([22, 18, 26, 19, 24])

In [22]:
np.linspace(-1,1,10)

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [57]:
data=np.random.random_integers(10,50,15).reshape((3,5))

<ipython-input-57-581715779084>:1: DeprecationWarning: This function is deprecated. Please call randint(10, 50 + 1) instead
  data=np.random.random_integers(10,50,15).reshape((3,5))


In [58]:
data

array([[12, 36, 17, 49, 29],
       [37, 19, 22, 21, 33],
       [12, 45, 23, 34, 27]])

In [59]:
data.sum(axis=0)

array([ 61, 100,  62, 104,  89])

In [60]:
data.sum(axis=1)

array([143, 132, 141])

In [61]:
data.min()

12

In [62]:
data.max()

49

In [63]:
data.mean()

27.733333333333334

In [64]:
data.argmax()

3

In [65]:
data.argmin()

0

In [79]:
array = np.arange(10,20)

In [80]:
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [81]:
array[:3]

array([10, 11, 12])

In [83]:
array[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [96]:
data[1,:]

array([37, 19, 22, 21, 33])

In [98]:
data[2,3]

34

In [100]:
data[:,0]

array([12, 37, 12])

In [103]:
data**2

array([[ 144, 1296,  289, 2401,  841],
       [1369,  361,  484,  441, 1089],
       [ 144, 2025,  529, 1156,  729]])

In [104]:
new_data=np.arange(-50,50)

In [105]:
new_data

array([-50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38,
       -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26, -25,
       -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12,
       -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,
         2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49])

In [106]:
new_data[new_data>0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [110]:
data.transpose()

array([[12, 37, 12],
       [36, 19, 45],
       [17, 22, 23],
       [49, 21, 34],
       [29, 33, 27]])

In [111]:
data.transpose().shape

(5, 3)

In [112]:
data.reshape((15,1))

array([[12],
       [36],
       [17],
       [49],
       [29],
       [37],
       [19],
       [22],
       [21],
       [33],
       [12],
       [45],
       [23],
       [34],
       [27]])

In [113]:
np.squeeze(data)

array([[12, 36, 17, 49, 29],
       [37, 19, 22, 21, 33],
       [12, 45, 23, 34, 27]])

In [125]:
np.delete(data, 1 ,0)

array([[12, 36, 17, 49, 29],
       [12, 45, 23, 34, 27]])

In [130]:
np.append(data,[[1, 2, 3], [[4, 5, 6], [7, 8, 9]]])

/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:1859: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return asanyarray(a).ravel(order=order)


array([12, 36, 17, 49, 29, 37, 19, 22, 21, 33, 12, 45, 23, 34, 27,
       list([1, 2, 3]), list([[4, 5, 6], [7, 8, 9]])], dtype=object)